
# This workflow builds FastJ Game Library on the latest version of Ubuntu using Gradle.

name: Build-Ubuntu

on:
  push:
    branches: [ 1.6.0 ]
  pull_request:
    branches: [ 1.6.0 ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build using Gradle
        run: ./gradlew build --info
